# Generated by Django 3.2.4 on 2021-06-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LMSUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='serial_num')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.IntegerField(max_length=11, verbose_name='telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='serial_num')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('addr', models.CharField(max_length=64, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='serial_num')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('ISBN', models.CharField(max_length=64, verbose_name='ISBN')),
                ('traslator', models.CharField(max_length=64, verbose_name='translator')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='serail_num')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('sex', models.CharField(max_length=4, verbose_name='sex')),
                ('age', models.IntegerField(default=0, verbose_name='age')),
                ('tel', models.CharField(max_length=64, verbose_name='Telephone')),
                ('book', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
